// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAS_qNxQPeLRDyqeoOEKzBphDa_UJze8w',
    appId: '1:77248230089:web:ceedd0a8c30135044a9318',
    messagingSenderId: '77248230089',
    projectId: 'putra-jaya-billiard',
    authDomain: 'putra-jaya-billiard.firebaseapp.com',
    storageBucket: 'putra-jaya-billiard.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEDyyOqYaWgsovtz2To7NoFIgvtgYtk6U',
    appId: '1:77248230089:android:f4e339a43b8a6e134a9318',
    messagingSenderId: '77248230089',
    projectId: 'putra-jaya-billiard',
    storageBucket: 'putra-jaya-billiard.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCea1b0NUgl89pyUxW1FuzVB0azxqkmeN8',
    appId: '1:77248230089:ios:c8b008473769945c4a9318',
    messagingSenderId: '77248230089',
    projectId: 'putra-jaya-billiard',
    storageBucket: 'putra-jaya-billiard.firebasestorage.app',
    iosBundleId: 'com.example.putraJayaBilliard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCea1b0NUgl89pyUxW1FuzVB0azxqkmeN8',
    appId: '1:77248230089:ios:c8b008473769945c4a9318',
    messagingSenderId: '77248230089',
    projectId: 'putra-jaya-billiard',
    storageBucket: 'putra-jaya-billiard.firebasestorage.app',
    iosBundleId: 'com.example.putraJayaBilliard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAS_qNxQPeLRDyqeoOEKzBphDa_UJze8w',
    appId: '1:77248230089:web:79b210148028960e4a9318',
    messagingSenderId: '77248230089',
    projectId: 'putra-jaya-billiard',
    authDomain: 'putra-jaya-billiard.firebaseapp.com',
    storageBucket: 'putra-jaya-billiard.firebasestorage.app',
  );

}